CREATE TABLE "User" (
    id SERIAL PRIMARY KEY,
    email VARCHAR(255) UNIQUE NOT NULL,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE "Post" (
    id SERIAL PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    authorId INT NOT NULL,
    CONSTRAINT fk_author FOREIGN KEY (authorId) REFERENCES "User"(id) ON DELETE CASCADE
);
